# Generated by Django 3.1.4 on 2020-12-26 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(max_length=20)),
                ('max_requests_per_month', models.IntegerField(blank=True, default=None, null=True)),
                ('max_requests_per_second', models.IntegerField(blank=True, default=None, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logic.project')),
            ],
            options={
                'db_table': 'project_ids',
            },
        ),
        migrations.CreateModel(
            name='AllowedClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(blank=True, default=None, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='urls.project')),
            ],
            options={
                'db_table': 'allowed_clients',
                'unique_together': {('project', 'ip')},
            },
        ),
        migrations.CreateModel(
            name='AllowedAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=42)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='urls.project')),
            ],
            options={
                'db_table': 'allowed_addresses',
                'unique_together': {('project', 'address')},
            },
        ),
    ]
