version: '3'
services:
  db:
    image: postgres:12.0-alpine
    restart: always
    container_name: adminurl-postgres
    expose:
      - 5432
  blockchain:
    image: trufflesuite/ganache-cli:latest
    ports:
      - ${RPC_PORT:-8545}:8545
    container_name: adminurl-blkchain
  adminurl:
    build:
      context: .
      dockerfile: Dockerfile
    image: adminurl:dev
    container_name: adminurl
    command: python main.py
    ports:
    - 80:80
    volumes:
    - .:/opt/project